package com.kitchenfantasy.model

case class Product (id: String,
                     name: String,
                     description: String,
                     price: Long,
                     imageUrl: String,
                     active: Boolean)


object ProductInventory {
  val productList = Array (
      Product ("1", "Heated Butter Knife",
        "Heated butter knife that slices through cold spreads smoothly",
        1295, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-01.jpg",
        true),
      Product ("2", "Ultimate Party Cooler",
        "The ultimate party cooler complete with a smart phone charger, bottle opener, and a blender",
        99, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-02.jpg",
        true),
      Product ("3", "Self cleaning hair brush",
        "Self cleaning hair brush",
        999, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-03.jpg",
        true),
      Product ("4", "Biolite camping stove",
        "Biolite camping stove uses the heat from burning wood to generate usable electricity via USB",
        99, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-041.jpg",
        true),
      Product ("5", "5 bladed one-handed scissors",
        "5 bladed one-handed scissors cuts herbs into adjustable sizes.",
        99, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-05.jpg",
        true),
      Product ("6", "5 bladed one-handed scissors",
        "5 bladed one-handed scissors cuts herbs into adjustable sizes.",
        99, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-06.jpg",
        true),
      Product ("7", "5 bladed one-handed scissors",
        "5 bladed one-handed scissors cuts herbs into adjustable sizes.",
        99, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-07.jpg",
        true),
      Product ("8", "5 bladed one-handed scissors",
        "5 bladed one-handed scissors cuts herbs into adjustable sizes.",
        99, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-08.jpg",
        true),
      Product ("9", "5 bladed one-handed scissors",
        "5 bladed one-handed scissors cuts herbs into adjustable sizes.",
        99, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-09.jpg",
        true),
      Product ("10", "5 bladed one-handed scissors",
        "5 bladed one-handed scissors cuts herbs into adjustable sizes.",
        99, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-10.jpg",
        true),
      Product ("11", "5 bladed one-handed scissors",
        "5 bladed one-handed scissors cuts herbs into adjustable sizes.",
        99, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-11.jpg",
        true),
      Product ("12", "5 bladed one-handed scissors",
        "5 bladed one-handed scissors cuts herbs into adjustable sizes.",
        99, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-12.jpg",
        true),
      Product ("13", "5 bladed one-handed scissors",
        "5 bladed one-handed scissors cuts herbs into adjustable sizes.",
        99, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-13.jpg",
        true),
      Product ("14", "5 bladed one-handed scissors",
        "5 bladed one-handed scissors cuts herbs into adjustable sizes.",
        99, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-14.jpg",
        true),
      Product ("15", "5 bladed one-handed scissors",
        "5 bladed one-handed scissors cuts herbs into adjustable sizes.",
        99, "http://cdn.architecturendesign.net/wp-content/uploads/2014/10/life-easier-clever-inventions-a-15.jpg",
        true)
      )
}